import 'react-native';
import {__testing} from '../src/WeatherContext';

const {fetchWeatherForAllCities} = __testing!;

beforeEach(() => {
  globalThis.fetch = jest.fn(() =>
    Promise.resolve({
      json: () =>
        Promise.resolve({
          cnt: 8,
          list: [
            {
              coord: {lon: 2.3488, lat: 48.8534},
              sys: {
                country: 'FR',
                timezone: 3600,
                sunrise: 1673336509,
                sunset: 1673367220,
              },
              weather: [
                {
                  id: 300,
                  main: 'Drizzle',
                  description: 'light intensity drizzle',
                  icon: '09d',
                },
                {id: 701, main: 'Mist', description: 'mist', icon: '50d'},
              ],
              main: {
                temp: 2,
                feels_like: 4.53,
                temp_min: 7.28,
                temp_max: 8.48,
                pressure: 1017,
                humidity: 96,
              },
              visibility: 5000,
              wind: {speed: 6.17, deg: 200},
              clouds: {all: 100},
              dt: 1673359755,
              id: 2988507,
              name: 'Paris',
            },
            {
              coord: {lon: -3.7026, lat: 40.4165},
              sys: {
                country: 'ES',
                timezone: 3600,
                sunrise: 1673336247,
                sunset: 1673370387,
              },
              weather: [
                {id: 800, main: 'Clear', description: 'clear sky', icon: '01d'},
              ],
              main: {
                temp: 10.87,
                feels_like: 9.84,
                temp_min: 8.59,
                temp_max: 13.48,
                pressure: 1028,
                humidity: 70,
              },
              visibility: 10000,
              wind: {speed: 1.54, deg: 240},
              clouds: {all: 0},
              dt: 1673359753,
              id: 3117735,
              name: 'Madrid',
            },
            {
              coord: {lon: -118.2437, lat: 34.0522},
              sys: {
                country: 'US',
                timezone: -28800,
                sunrise: 1673362740,
                sunset: 1673398890,
              },
              weather: [
                {id: 701, main: 'Mist', description: 'mist', icon: '50n'},
              ],
              main: {
                temp: 14.01,
                feels_like: 13.92,
                temp_min: 12.27,
                temp_max: 15.77,
                pressure: 1019,
                humidity: 94,
              },
              visibility: 6437,
              wind: {speed: 6.17, deg: 150},
              clouds: {all: 100},
              dt: 1673360093,
              id: 5368361,
              name: 'Los Angeles',
            },
            {
              coord: {lon: -71.0598, lat: 42.3584},
              sys: {
                country: 'US',
                timezone: -18000,
                sunrise: 1673352756,
                sunset: 1673386219,
              },
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'broken clouds',
                  icon: '04d',
                },
              ],
              main: {
                temp: 2.76,
                feels_like: -1.27,
                temp_min: 1.27,
                temp_max: 3.94,
                pressure: 1015,
                humidity: 69,
              },
              visibility: 10000,
              wind: {speed: 4.63, deg: 290},
              clouds: {all: 75},
              dt: 1673360064,
              id: 4930956,
              name: 'Boston',
            },
            {
              coord: {lon: -74.006, lat: 40.7143},
              sys: {
                country: 'US',
                timezone: -18000,
                sunrise: 1673353169,
                sunset: 1673387220,
              },
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'overcast clouds',
                  icon: '04d',
                },
              ],
              main: {
                temp: 3.51,
                feels_like: 0.02,
                temp_min: 1.75,
                temp_max: 4.99,
                pressure: 1018,
                humidity: 67,
              },
              visibility: 10000,
              wind: {speed: 4.02, deg: 360},
              clouds: {all: 100},
              dt: 1673360077,
              id: 5128581,
              name: 'New York',
            },
            {
              coord: {lon: 103.8501, lat: 1.2897},
              sys: {
                country: 'SG',
                timezone: 28800,
                sunrise: 1673305808,
                sunset: 1673349187,
              },
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'broken clouds',
                  icon: '04n',
                },
              ],
              main: {
                temp: 25.97,
                feels_like: 25.97,
                temp_min: 25.61,
                temp_max: 28.35,
                pressure: 1012,
                humidity: 86,
              },
              visibility: 10000,
              wind: {speed: 2.06, deg: 20},
              clouds: {all: 75},
              dt: 1673359754,
              id: 1880252,
              name: 'Singapore',
            },
            {
              coord: {lon: 19.9167, lat: 50.0833},
              sys: {
                country: 'PL',
                timezone: 3600,
                sunrise: 1673332601,
                sunset: 1673362693,
              },
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'broken clouds',
                  icon: '04d',
                },
              ],
              main: {
                temp: 4.4,
                feels_like: 4.4,
                temp_min: 3.63,
                temp_max: 4.9,
                pressure: 1016,
                humidity: 95,
              },
              visibility: 7000,
              wind: {speed: 1.03, deg: 0},
              clouds: {all: 75},
              dt: 1673359759,
              id: 3094802,
              name: 'Krakow',
            },
            {
              coord: {lon: 17.0333, lat: 51.1},
              sys: {
                country: 'PL',
                timezone: 3600,
                sunrise: 1673333562,
                sunset: 1673363117,
              },
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'broken clouds',
                  icon: '04d',
                },
              ],
              main: {
                temp: 6.19,
                feels_like: 2.76,
                temp_min: 5.51,
                temp_max: 6.9,
                pressure: 1021,
                humidity: 87,
              },
              visibility: 10000,
              wind: {speed: 5.14, deg: 300},
              clouds: {all: 75},
              dt: 1673359759,
              id: 3081368,
              name: 'Wroclaw',
            },
          ],
        }),
    }),
  ) as any;
});

it('fetchWeatherForAllCities to resolve with expected output', async () => {
  const result = await fetchWeatherForAllCities();

  expect(result).toStrictEqual([
    {
      clouds: 100,
      condition: 'Drizzle',
      humidity: 96,
      icon: '09d',
      id: 2988507,
      name: 'Paris',
      pressure: 1017,
      temperature: 2,
      windSpeed: 6.17,
    },
    {
      clouds: 0,
      condition: 'Clear',
      humidity: 70,
      icon: '01d',
      id: 3117735,
      name: 'Madrid',
      pressure: 1028,
      temperature: 10.87,
      windSpeed: 1.54,
    },
    {
      clouds: 100,
      condition: 'Mist',
      humidity: 94,
      icon: '50n',
      id: 5368361,
      name: 'Los Angeles',
      pressure: 1019,
      temperature: 14.01,
      windSpeed: 6.17,
    },
    {
      clouds: 75,
      condition: 'Clouds',
      humidity: 69,
      icon: '04d',
      id: 4930956,
      name: 'Boston',
      pressure: 1015,
      temperature: 2.76,
      windSpeed: 4.63,
    },
    {
      clouds: 100,
      condition: 'Clouds',
      humidity: 67,
      icon: '04d',
      id: 5128581,
      name: 'New York',
      pressure: 1018,
      temperature: 3.51,
      windSpeed: 4.02,
    },
    {
      clouds: 75,
      condition: 'Clouds',
      humidity: 86,
      icon: '04n',
      id: 1880252,
      name: 'Singapore',
      pressure: 1012,
      temperature: 25.97,
      windSpeed: 2.06,
    },
    {
      clouds: 75,
      condition: 'Clouds',
      humidity: 95,
      icon: '04d',
      id: 3094802,
      name: 'Krakow',
      pressure: 1016,
      temperature: 4.4,
      windSpeed: 1.03,
    },
    {
      clouds: 75,
      condition: 'Clouds',
      humidity: 87,
      icon: '04d',
      id: 3081368,
      name: 'Wroclaw',
      pressure: 1021,
      temperature: 6.19,
      windSpeed: 5.14,
    },
  ]);
});
