name: E2E tests Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-12
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Android E2E build cache
        uses: actions/cache@v2
        with:
          path: |
            android/.gradle
            android/app/build
          key: ${{ runner.os }}-android-e2e-build

      - name: Detox build Android
        run: yarn detox build --configuration android.emu.release

      - name: Run Detox tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: aosp_atd
          channel: canary
          arch: x86
          profile: pixel
          avd-name: Pixel_3a_API_30_AOSP
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: yarn detox test --configuration android.emu.release -l verbose --headless
