name: TypeScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  TypeScript:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run TypeScript
        run: yarn typescript
